apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-frontend
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      containers:
      - name: llm-frontend
        image: llm-chatbot-frontend:local
        ports:
        - containerPort: 80
